apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-tracker.labels" . | nindent 4 }}
    {{- include "task-tracker.selectorLabels" (dict "component" "backend") | nindent 4 }}
spec:
  selector:
    {{- include "task-tracker.selectorLabels" (dict "component" "backend") | nindent 4 }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
