apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-tracker.labels" . | nindent 4 }}
    {{- include "task-tracker.selectorLabels" (dict "component" "postgres") | nindent 4 }}
spec:
  # Headless service for StatefulSet — each pod gets a stable DNS name
  clusterIP: None
  selector:
    {{- include "task-tracker.selectorLabels" (dict "component" "postgres") | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
