apiVersion: v1
kind: Secret
metadata:
  name: task-tracker-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}?schema=public"
  JWT_ACCESS_SECRET: {{ .Values.backend.jwtAccessSecret | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
